version: '3'

services:

   

  server:
    build: 
      context: ./server
    ports:
      - "50051:50051"
    depends_on:
      - mariadb
    
    

  client:
    build: 
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
 
       
  envoy:
    build:
      context: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - "server"
      - "client"
   
  
  mariadb:
    build: 
      context: ./mariadb
    ports:
      - "3306:3306"
    
    
    