version: '3'

services:

  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client

   

  server:
    build: 
      context: ./server
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    

  client:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - envoy
 
       
  envoy:
    build:
      context: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - "server"
   
  
  mariadb:
    build: 
      context: ./mariadb
    ports:
      - "3306:3306"
    
    
    