version: '3'

services:

  server:
    build: 
      context: ./server
    ports:
      - "9000:9000"
    links:
      - "mariadb"
    container_name: "server"

  client:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    tty: true
    links:
      - "envoy"
    container_name: "nextjs"
       
  envoy:
    build:
      context: ./proxy
    ports:
      - "8080:8080"
    links:
      - "server"
    container_name: "envoy"
  
  mariadb:
    build: 
      context: ./mariadb
    ports:
      - "3306:3306"
    container_name: "mariadb"
    
    