import Head from 'next/head'
import styles from "../styles/home.module.scss"
import {VideoHTMLAttributes} from "react"
import Link from 'next/link'


const videoProps ={
  children: <source src='/video/home.mp4' type='video/mp4' />,
  autoPlay:true,
  muted: true,
  loop: true
}

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="global_container">


      <div className={styles.video_box}>
      <video {...(videoProps as VideoHTMLAttributes<HTMLVideoElement>)}>
        <source src="/video/home.mp4" type="video/mp4" />
      </video>
      </div>



      <div className="normal_container">

        <div className={styles.eyecatchtext_box}>

          <h1>感動と喜びを<p/>
          届けられる技術者に
          </h1>
          <h3>/ kimura ryotaのポートフォリオ</h3>
          <h2>Full-Stack Developer</h2>

        </div>


      

      <div className={styles.header_box}>
      <header>
        <nav>
          <ul>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/skills">Skills</Link></li>
            <li><Link href="/project">Project</Link></li>
            <li><Link href="/news">News</Link></li>
            <li><Link href="/contact">Contact</Link></li>
          </ul>
        </nav>
      </header>
      </div>
      </div>

      <div>
      </div>

      </div>
    </>
  )
}
